#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

Yellow='\033[0;33m'
NC='\033[0m'

# yarn lint:ts

# yarn lint:scss

# yarn test:unit

echo -e "\n\n 💡 ${Yellow} Build production project ${NC} \n"

yarn build:prod

echo -e "\n\n 💡 ${Yellow} Build storybook ${NC} \n"
yarn sb:build

echo -e "\n\n 🎉 Success! \n" 
